#!/bin/sh
FQBN=esp32:esp32:pico32:PartitionScheme=no_ota,DebugLevel=info
PORT=/dev/ttyUSB1
PORTM=/dev/ttyUSB0
CLEAN=--clean

if [ -z "$1" ]; then
	echo "Usage: sketch build|upload|test"
	exit
fi

if [[ "$1" == "build" ]]; then
	TMPDIR=./tmp arduino-cli compile -e ${CLEAN} \
	--fqbn $FQBN
	retVal=$?
	if [ $retVal -ne 0 ]; then
	    exit
	fi
#	--libraries ./libs/ESPAsyncWebServer-menodev 
    shift
fi

if [[ "$1" == "upload" ]]; then
	TMPDIR=./tmp arduino-cli upload  \
	    --fqbn $FQBN \
	    --port $PORT
    shift
fi

if [[ "$1" == "test" ]]; then
    HTTPCODE=`curl  -s -o /dev/null -w "%{http_code}" "http://sdwifi.local/ping" `
    if [[ $HTTPCODE  -ne 200 ]]; then
	echo "ping HTTP ${HTTPCODE}"
	exit
    fi

    dd if=/dev/zero of=./tmp/dummy.bin bs=1024 count=4096 2> /dev/null
    sha1sum -b ./tmp/dummy.bin > ./tmp/dummy.sha1
    HTTPCODE=`curl  -s -o /dev/null -w "%{http_code}" "http://sdwifi.local/remove?path=test01.bin" `
    if [[ $HTTPCODE  -ne 200 && $HTTPCODE  -ne 404 ]]; then
	echo "remove HTTP ${HTTPCODE}"
	exit
    fi
    HTTPCODE=`curl  -s -o /dev/null -w "%{http_code}" "http://sdwifi.local/remove?path=test02.bin" `
    if [[ $HTTPCODE  -ne 200 && $HTTPCODE  -ne 404 ]]; then
	echo "remove HTTP ${HTTPCODE}"
	exit
    fi
    HTTPCODE=`curl  -s -o /dev/null -w "%{http_code}" -F "data=@./tmp/dummy.bin" "http://sdwifi.local/upload?path=test01.bin" `
    if [ $HTTPCODE  -ne 200 ]; then
	echo "upload HTTP ${HTTPCODE}"
	exit
    fi
    HTTPCODE=`curl  -s -o /dev/null -w "%{http_code}" "http://sdwifi.local/list?path=test01.bin" `
    if [ $HTTPCODE  -ne 200 ]; then
	echo "list HTTP ${HTTPCODE}"
	exit
    fi
    rm ./tmp/dummy.bin

    HTTPCODE=`curl  -s -o /dev/null -w "%{http_code}" "http://sdwifi.local/rename?from=test01.bin&to=test02.bin" `
    if [ $HTTPCODE  -ne 200 ]; then
	echo "rename HTTP ${HTTPCODE}"
	exit
    fi
    HTTPCODE=`curl  -s -o ./tmp/dummy.bin -w "%{http_code}" "http://sdwifi.local/download?path=test02.bin" `
    if [ $HTTPCODE  -ne 200 ]; then
	echo "download HTTP ${HTTPCODE}"
	exit
    fi
    sha1sum -c ./tmp/dummy.sha1
    retVal=$?
    if [ $retVal -ne 0 ]; then
        echo "sha1 sum failed"
        exit
    fi
    rm ./tmp/dummy.bin ./tmp/dummy.sha1
    curl "http://sdwifi.local/info" | jq
fi

if [[ "$1" == "monitor" ]]; then
    if [[ $2 ]]; then
	PORT=$2
    fi
    arduino-cli monitor --port $PORTM --config baudrate=115200,rts=off,dtr=off
fi
